// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx6i10FjZwM2_dh1VBfXD7uYUjEfh7H-M',
    appId: '1:165524948757:web:952adfc72b5263580f8b1c',
    messagingSenderId: '165524948757',
    projectId: 'chatapp-9ff0a',
    authDomain: 'chatapp-9ff0a.firebaseapp.com',
    storageBucket: 'chatapp-9ff0a.appspot.com',
    measurementId: 'G-7QZ45HEPQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUCOXz2eVZkCsNsZNWAQFV6QoZCtVg4s0',
    appId: '1:165524948757:android:5df223893b86c1a90f8b1c',
    messagingSenderId: '165524948757',
    projectId: 'chatapp-9ff0a',
    storageBucket: 'chatapp-9ff0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTpvddVQAQ6uwZvM-373XqiLLTypJvntU',
    appId: '1:165524948757:ios:551d1d7126083ea50f8b1c',
    messagingSenderId: '165524948757',
    projectId: 'chatapp-9ff0a',
    storageBucket: 'chatapp-9ff0a.appspot.com',
    iosClientId: '165524948757-dkgcpds46kdvhlssdop6421k9k0pgtn6.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupsChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTpvddVQAQ6uwZvM-373XqiLLTypJvntU',
    appId: '1:165524948757:ios:8f31e9ad9a7cfd640f8b1c',
    messagingSenderId: '165524948757',
    projectId: 'chatapp-9ff0a',
    storageBucket: 'chatapp-9ff0a.appspot.com',
    iosClientId: '165524948757-ia2geti81ii34t9p2475e380p5hvcubf.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupsChat.RunnerTests',
  );
}
